# 1. PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_db
spring.datasource.username=postgres
spring.datasource.password=Raju@123
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate / JPA Schema Auto-Generation Strategy
# This tells Hibernate to check our entity annotations and build the tables automatically!
spring.jpa.hibernate.ddl-auto=update

# 3. SQL Logging Dashboard (Great for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true