# 1. PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://ep-tiny-cloud-azzc755y-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fUeTjoF5Bgz7
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate / JPA Schema Auto-Generation Strategy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# 4. JWT SECURITY CONFIGURATION
# Secret key
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Access Token expiration: 15 minutes = 900000 ms
application.security.jwt.expiration=900000
# Refresh Token expiration: 7 days = 604800000 ms
application.security.jwt.refresh-token.expiration=604800000